### ISSUE TITLE
Background image tiles regardless

### ISSUE THREAD

**Issue by rightsaidjames** [Autophagy/twitter-bg-restorer#1]
I have installed this extension and managed to get my old background image back on my timeline, but despite unticking the 'tile background' option it's still tiled:
![2015-07-21 11_59_32- 2 twitter](https://cloud.githubusercontent.com/assets/3018395/8799289/f41583ac-2fa0-11e5-9ef9-3ff6cda3a4a4.png)

My options are as follows:
![2015-07-21 11_59_52-twitter background restorer options](https://cloud.githubusercontent.com/assets/3018395/8799294/fbfa1ccc-2fa0-11e5-8a4d-4e3a9d07e37a.png)

Looking through the code it seems like the fix is to specify an `else` condition that returns `body.style.backgroundRepeat = 'no-repeat';` when `items.backgroundTile` is false, but as I don't know how to compile Chrome extensions (so wouldn't be able to test this) I'll leave that with you if that's okay?

**Comment by autophagy** [comment]
Sure! Thanks for pointing this out, I'll get it fixed

**Comment by rightsaidjames** [comment]
Reinstalled the extension and confirmed as fixed :)
