### ISSUE TITLE
Background changes on https://dev.twitter.com or https://help.twitter.com

### ISSUE THREAD

**Issue by AdamCarballo** [Autophagy/twitter-bg-restorer#14]
The **manifest.json** allows the extension to work on any "http/https//:*.twitter.com/" site, therefore also affects **dev.twitter.com** and **help.twitter.com**, making them unreadable if your color conflicts with the font color.

I would recommend to block the permissions on dev and help subdomains to avoid this issue.

**Comment by autophagy** [comment]
@AdamEC Super sorry about the late reply - thank you for bringing this to my attention. I'll fix this up :slightly_smiling_face:

**Comment by autophagy** [comment]
@AdamEC This should now be in 2.1.0. Thanks for reporting!
