### ISSUE TITLE
Add support for "The New Twitter" (2019 Design)?

### ISSUE THREAD

**Issue by Seffuel** [Autophagy/twitter-bg-restorer#15]
Twitter is about to change it's layout to a more simple look. Sadly it locks out the extension that you created and was hoping you could fix that problem by pushing an Update

**Comment by autophagy** [comment]
@Seffuel Thank you for bringing this up - i'll take a look at the new layout and create a new version for it.

**Comment by autophagy** [comment]
@Seffuel Hi! This is now in version 2.1.0, which is up on the chrome store (and should be on the firefox addons store soon). Could you let me know if this solves it for you?

It works for me, but the way I've done it seems a little fragile. Would be good to know if it works for you too :slightly_smiling_face:

**Comment by Seffuel** [comment]
I can confirm that it works and the new twitter design looks a 100 times better now! Thanks you for updating your extension. Whatever you did, it works. Awesome work :D 
https://imgur.com/a/Oi62yHl

**Comment by autophagy** [comment]
Awesome, glad to hear it. Thank you!
