### ISSUE TITLE
Hello I was wondering what is the resolution?

### ISSUE THREAD

**Issue by CraftyArmy** [Autophagy/twitter-bg-restorer#17]
I`m been wondering do you have a recommended resolution size for custom images using stretch? Or is there only one good resolution for this extension?

**Comment by autophagy** [comment]
@CraftyArmy The recommended image size would be the size of your browser window.  always have my browser fullscreen, so the image size I use is my monitor's resolution (3840x2160).

I'd therefore recommend an image that's close in resolution to your screen :slightly_smiling_face:

**Comment by CraftyArmy** [comment]
> @CraftyArmy The recommended image size would be the size of your browser window. always have my browser fullscreen, so the image size I use is my monitor's resolution (3840x2160).
> 
> I'd therefore recommend an image that's close in resolution to your screen 🙂

@autophagy Thank You For The Help!!

**Comment by autophagy** [comment]
@CraftyArmy No worries! Thank you for reaching out and using my addon :slightly_smiling_face:
