### ISSUE TITLE
Fix this to work on "x.com"?

### ISSUE THREAD

**Issue by tehFoxx0rz** [Autophagy/twitter-bg-restorer#20]
I love this extension and have been using it for a long time now. Even after Twitter got renamed to "x", it still worked because the main page was still "twitter.com".

However, it looks like just today, that finally got changed so that "twitter.com" redirects all URLs to "x.com". Which, breaks this lovely addon!

The site itself still seems to function the same, so it would be lovely if I could keep using it. Thanks.

**Comment by autophagy** [comment]
Thanks to @lolLucoa, this should be fixed with https://github.com/autophagy/twitter-bg-restorer/pull/19. I think I need to fix a few things to upload a new version, and I'll try and do that today or tomorrow. Will close this when I've uploaded a new version!

**Comment by tehFoxx0rz** [comment]
It seems to be working for me now, thank you so much!
